---

minimum_pre_commit_version: 2.9.3

repos:

  # Check if we might need to run pip-compile to compile any requirements input
  # files to requirements text files.
  #
  # The pip-tools docs suggest a pre-commit hook for this (which actually does
  # the compilation too), but we use this hook instead, because of [1] and also
  # because the suggested hook doesn't seem to handle multiple inputs simply.
  #
  # [1] https://github.com/jazzband/pip-tools/issues/1208
  - repo: https://github.com/MartinThoma/check-pip-compile
    rev: 0.1.0
    hooks:
    -   id: check-pip-compile
        name: Check if pip requirements files need recompiling
        args: ['requirements.in', 'requirements-dev.in']

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.9.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-blind-except==0.1.1
          - flake8-bugbear==20.11.1
          - flake8-builtins==1.5.3
          - flake8-comprehensions==3.3.1
          - flake8-debugger==4.0.0
          - flake8-executable==2.1.1
          - flake8-logging-format==0.6.0
          - flake8-mutable==1.2.0
          - flake8-pie==0.6.1
          - flake8-print==4.0.0
          - flake8-pytest==1.3
          - flake8-string-format==0.3.0
          - pep8-naming==0.11.1
          # Unsure if want
          # - flake8-eradicate         # Too brutal?
          # - flake8-rst-docstrings
          # Do not want
          # - flake8-commas            # Clashes with black
          # - flake8-docstrings        # Fails to run
        types: [file, python]

  - repo: git@github.com:pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
        exclude: '.bumpversion.cfg|.*\.csv'
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: check-symlinks
      - id: debug-statements
        types: [file, python]
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: .bumpversion.cfg
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]

  - repo: https://github.com/ambv/black
    rev: 21.4b2
    hooks:
      - id: black
        language_version: python3.9

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        additional_dependencies:
          - pyproject
          - toml
        types: [file, python]

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.812
    hooks:
      - id: mypy
        additional_dependencies:
          - 'pydantic'
